# Generated by Django 4.0.5 on 2022-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='rate',
            new_name='dbp',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='name',
        ),
        migrations.AddField(
            model_name='rates',
            name='tbp',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
